const data = {
  appbar: [
    {
      id: "1",
      theme_id: "1",
      mode: "appbar",
      name: "Appbar 1",
      styles: {
        icon: "abacus",
        bottom: "",
        layout: null,
        shadow: 1,
        shape_type: "square",
        center_title: 0,
        title_spacing: 0,
        flexible_space: "",
        selected_color: "#4f46e5",
        icon_theme_size: 12,
        toolbar_opacity: 0,
        background_color: "#4f46e5",
        icon_theme_color: "#4f46e5",
        unselected_color: "#4f46e5",
        shape_border_radius: 0,
        actions_icon_theme_size: 0,
        actions_icon_theme_color: "#4f46e5",
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: "abacus",
        bottom: "",
        layout: null,
        shadow: 1,
        shape_type: "square",
        center_title: 0,
        title_spacing: 0,
        flexible_space: "",
        selected_color: "#4f46e5",
        icon_theme_size: 12,
        toolbar_opacity: 0,
        background_color: "#ffffffff",
        icon_theme_color: "#4f46e5",
        unselected_color: "#4f46e5",
        shape_border_radius: 0,
        actions_icon_theme_size: 0,
        actions_icon_theme_color: "#4f46e5",
        automatically_imply_leading: 0,
      },
      active: "yes",
      components: [
        {
          id: "1",
          name: "Drawer button",
          slug: "drawer-button",
          properties: {
            name: "Drawer button",
            slug: "drawer-button",
            event: "open-drawer",
            label: "Drawer button",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: "menu-2",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: "leading_area",
          },
          customize_properties: {
            name: "Drawer button",
            slug: "drawer-button",
            event: "open-drawer",
            label: "Drawer button",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: "menu-2",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: "leading_area",
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          component_position: "leading_area",
        },
        {
          id: "2",
          name: "Aappify",
          slug: "aappify",
          properties: {
            name: "Aappify",
            slug: "aappify",
            event: null,
            label: "Aappify",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: null,
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "Text",
            selected_design: null,
            component_position: "title_area",
          },
          customize_properties: {
            name: "Aappify",
            slug: "aappify",
            event: null,
            label: "Aappify",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: null,
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "Text",
            selected_design: null,
            component_position: "title_area",
          },
          styles: {
            text_decoration: {
              color: "#000000",
              font_size: "24",
              text_font: "Lato",
              font_style: "normal",
              margin_top: "5",
              font_family: "Lato",
              font_weight: "bold",
              margin_left: "5",
              padding_top: "5",
              margin_right: "5",
              padding_left: "5",
              margin_bottom: "5",
              padding_right: "5",
              text_overflow: "ellipsis",
              letter_spacing: "1.5",
              padding_bottom: "5",
              background_color: "#808080",
            },
          },
          customize_styles: {
            text_decoration: {
              color: "#000000",
              font_size: "24",
              text_font: "Lato",
              font_style: "normal",
              margin_top: "5",
              font_family: "Lato",
              font_weight: "bold",
              margin_left: "5",
              padding_top: "5",
              margin_right: "5",
              padding_left: "5",
              margin_bottom: "5",
              padding_right: "5",
              text_overflow: "ellipsis",
              letter_spacing: "1.5",
              padding_bottom: "5",
              background_color: "#808080",
            },
          },
          component_position: "title_area",
        },
        {
          id: "3",
          name: "Notification button",
          slug: "notification-button",
          properties: {
            name: "Notification button",
            slug: "notification-button",
            event: null,
            label: "Notification button",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: "bell",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: "action_area",
          },
          customize_properties: {
            name: "Notification button",
            slug: "notification-button",
            event: null,
            label: "Notification button",
            scope: '["appbar"]',
            web_icon: null,
            icon_code: "school-bell",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: "action_area",
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#f77979ff",
              weight: "2.0",
            },
          },
          component_position: "action_area",
        },
      ],
      properties: null,
      customize_properties: null,
    },
    {
      id: "2",
      theme_id: "1",
      mode: "appbar",
      name: "Appbar 2",
      styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      active: "no",
      components: [],
      properties: null,
      customize_properties: null,
    },
    {
      id: "3",
      theme_id: "1",
      mode: "appbar",
      name: "Appbar-3",
      styles: {
        icon: "abacus",
        bottom: "",
        layout: null,
        shadow: 1,
        shape_type: "square",
        center_title: 0,
        title_spacing: 0,
        flexible_space: "",
        selected_color: "#4f46e5",
        icon_theme_size: 12,
        toolbar_opacity: 0,
        background_color: "#4f46e5",
        icon_theme_color: "#4f46e5",
        unselected_color: "#4f46e5",
        shape_border_radius: 0,
        actions_icon_theme_size: 0,
        actions_icon_theme_color: "#4f46e5",
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: "abacus",
        bottom: "",
        layout: null,
        shadow: 1,
        shape_type: "square",
        center_title: 0,
        title_spacing: 0,
        flexible_space: "",
        selected_color: "#4f46e5",
        icon_theme_size: 12,
        toolbar_opacity: 0,
        background_color: "#4f46e5",
        icon_theme_color: "#4f46e5",
        unselected_color: "#4f46e5",
        shape_border_radius: 0,
        actions_icon_theme_size: 0,
        actions_icon_theme_color: "#4f46e5",
        automatically_imply_leading: 0,
      },
      active: "no",
      components: [],
      properties: null,
      customize_properties: null,
    },
  ],
  navbar: [
    {
      id: "4",
      theme_id: "1",
      mode: "navbar",
      name: "Navbar-1",
      styles: {
        icon: null,
        bottom: null,
        layout: "navbar-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#f7f6f4",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: null,
        bottom: null,
        layout: "navbar-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#f7f6f4",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      active: "yes",
      components: [
        {
          id: "4",
          name: "Home page button",
          slug: "home-page-button",
          properties: {
            name: "Home page button",
            slug: "home-page-button",
            event: "home-page",
            label: "Home page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "home-2",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          customize_properties: {
            name: "Home page button",
            slug: "home-page-button",
            event: "home-page",
            label: "Home page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "home-2",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          component_position: null,
        },
        {
          id: "5",
          name: "Category page button",
          slug: "category-page-button",
          properties: {
            name: "Category page button",
            slug: "category-page-button",
            event: "category-page",
            label: "Category page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "category",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          customize_properties: {
            name: "Category page button",
            slug: "category-page-button",
            event: "category-page",
            label: "Category page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "category",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          component_position: null,
        },
        {
          id: "6",
          name: "Cart page button",
          slug: "cart-page-button",
          properties: {
            name: "Cart page button",
            slug: "cart-page-button",
            event: "cart-page",
            label: "Cart page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "shopping-cart",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          customize_properties: {
            name: "Cart page button",
            slug: "cart-page-button",
            event: "cart-page",
            label: "Cart page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "shopping-cart",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          component_position: null,
        },
        {
          id: "7",
          name: "Dashboard page button",
          slug: "dashboard-page-button",
          properties: {
            name: "Dashboard page button",
            slug: "dashboard-page-button",
            event: "dashboard-page",
            label: "Dashboard page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "layout-dashboard",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          customize_properties: {
            name: "Dashboard page button",
            slug: "dashboard-page-button",
            event: "dashboard-page",
            label: "Dashboard page button",
            scope: '["navbar"]',
            web_icon: null,
            icon_code: "layout-dashboard",
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "IconButton",
            selected_design: null,
            component_position: null,
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            icon_decoration: {
              size: "24",
              color: "#000000",
              weight: "2.0",
            },
          },
          component_position: null,
        },
      ],
      properties: null,
      customize_properties: null,
    },
    {
      id: "5",
      theme_id: "1",
      mode: "navbar",
      name: "Navbar-2",
      styles: {
        icon: null,
        bottom: null,
        layout: "navbar-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#f7f6f4",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: null,
        bottom: null,
        layout: "navbar-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#f7f6f4",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      active: "no",
      components: [],
      properties: null,
      customize_properties: null,
    },
  ],
  drawer: [
    {
      id: "6",
      theme_id: "1",
      mode: "drawer",
      name: "Drawer-1",
      styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-one",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      active: "yes",
      components: [
        {
          id: "8",
          name: "Drawer category",
          slug: "drawer-category",
          properties: {
            name: "Drawer category",
            slug: "drawer-category",
            event: null,
            label: "Drawer category",
            scope: '["drawer"]',
            web_icon: null,
            icon_code: null,
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "ListViewVertical",
            selected_design: null,
            component_position: null,
          },
          customize_properties: {
            name: "Drawer category",
            slug: "drawer-category",
            event: null,
            label: "Drawer category",
            scope: '["drawer"]',
            web_icon: null,
            icon_code: null,
            image_url: null,
            class_type: null,
            is_multiple: 0,
            layout_type: "ListViewVertical",
            selected_design: null,
            component_position: null,
          },
          styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            image_decoration: {
              color: "#000000",
              width: "0.3",
              boxfit: "cover",
              height: "0.3",
              radius: "0",
              alignment: "center",
            },
            list_view_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            name_text_decoration: {
              color: "#000000",
              font_size: "24",
              font_style: "normal",
              font_family: "Lato",
              font_weight: "bold",
              text_overflow: "ellipsis",
              letter_spacing: "1.5",
              background_color: "#808080",
            },
          },
          customize_styles: {
            box_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            image_decoration: {
              color: "#000000",
              width: "0.3",
              boxfit: "cover",
              height: "0.3",
              radius: "0",
              alignment: "center",
            },
            list_view_decoration: {
              margin_top: "5",
              margin_left: "5",
              padding_top: "5",
              border_color: "#000000",
              border_width: "0",
              margin_right: "5",
              padding_left: "5",
              shadow_color: "#808080",
              border_radius: "0",
              margin_bottom: "5",
              padding_right: "5",
              padding_bottom: "5",
              shadow_offset_x: "0",
              shadow_offset_y: "0",
              background_color: "#808080",
              shadow_blur_radius: "0",
            },
            name_text_decoration: {
              color: "#000000",
              font_size: "24",
              font_style: "normal",
              font_family: "Lato",
              font_weight: "bold",
              text_overflow: "ellipsis",
              letter_spacing: "1.5",
              background_color: "#808080",
            },
          },
          component_position: null,
        },
      ],
      properties: null,
      customize_properties: null,
    },
    {
      id: "7",
      theme_id: "1",
      mode: "drawer",
      name: "Drawer-2",
      styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-two",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      customize_styles: {
        icon: "menu",
        bottom: null,
        layout: "drawer-two",
        shadow: null,
        shape_type: null,
        center_title: 0,
        title_spacing: null,
        flexible_space: null,
        selected_color: "#4f46e5",
        icon_theme_size: null,
        toolbar_opacity: null,
        background_color: "#4f46e5",
        icon_theme_color: null,
        unselected_color: "#4f46e5",
        shape_border_radius: null,
        actions_icon_theme_size: null,
        actions_icon_theme_color: null,
        automatically_imply_leading: 0,
      },
      active: "no",
      components: [],
      properties: null,
      customize_properties: null,
    },
  ],
};

export default data;